# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92abc0cd4336abb8755a6b84820c665516edf9bf9e83984a7d9e635843afdf86d82ce34fdc2c9f2fdf6526fd46e23eeafe110dff01cd0192c9e709ae8001f528

test:
  secret_key_base: 9d75e2171c2a09452e3c6ef86731f626511139ba6f12341bcccf30841852cb5bf78bdd28075cbb1fab2431857d490156ace8f33b292d213600bc67f6dd8cad63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
