source 'https://rubygems.org'
ruby '2.2.1'

gem 'rails', '4.2.3'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise'
gem 'chosen-rails'
# gem 'jquery-turbolinks'
gem 'compass', '1.0.3'
gem 'compass-rails', '2.0.4'
gem 'bootstrap-sass'

gem 'pry', '~> 0.10.1'

gem 'acts_as_votable', '~> 0.10.0'
gem 'will_paginate', '~> 3.0.7'

gem 'paperclip', '~> 4.3.1'
gem 'aws-sdk', '< 2.0'
gem 'paperclip-av-transcoder'
gem "paperclip-ffmpeg", "~> 1.2.0"
gem 'av', '0.9.0'

group :development, :test do
	gem 'sqlite3'
	gem 'byebug'
	gem 'web-console', '~> 2.0'
	gem 'spring'
end

group :production do
	gem 'pg'
	gem 'rails_12factor'
	gem "rmagick", "~> 2.13.2"
end

