# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9d3550da31d0f04e10c0e69e2afe3da189871af05ef8cff2eed15aa9a0c6379cff62a4e51dc75f11d1cf2287b3d175995f49253e615c3f08db2258d26615f0d

test:
  secret_key_base: cd85dd5c6db1e6362257867c7b807aa0cb03a8ab0f2932d021ff17a8b3c2322e495e02834c9a53722c37084dc37f87d2b5cc87046cf24d98cea0cb420ca37258

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
